### ISSUE TITLE
Cannot run koop now

### ISSUE THREAD

**Issue by jkerr5** [koopjs/FeatureServer#105]
When I install from scratch and try to run a koop provider, I now get the following stack trace

```
module.js:557
    throw err;
    ^

Error: Cannot find module 'featureserver'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/projects/koop-sample-app/node_modules/koop-output-geoservices/index.js:1:83)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

This happens for both the MarkLogic provider I am working on as well as the koop-sample-app. The `featureserver` directory is there but there is no `dist` folder after running `npm install`.

**Comment by jkerr5** [comment]
I can get things to run again by setting an explicit dependency on featureserver 2.11.1.

**Comment by rgwozdz** [comment]
Patch on the way.  Sorry, it got npm published without a compile.

**Comment by rgwozdz** [comment]
Just published a patch (v2.12.1).  This time, compiled, with the result `dist` directory. You can upgrade with `yarn upgrade`.
