### ISSUE TITLE
Support space in orderByFields separator

### ISSUE THREAD

**Issue by jkerr5** [koopjs/FeatureServer#116]
ArcGIS Pro uses a comma plus a space `, ` as a separator when multiple `orderByFields` are specified. Koop throws the following 500 error with requests like this though:
```
{"error":"Parse error on line 1:\n...rties->`domain` ASC,\n-----------------------^\nExpecting 'LITERAL', 'BRALITERAL', 'LPAR', 'NUMBER', 'STRING', 'SHARP', 'DOLLAR', 'AT', 'VALUE', 'COLON', 'NOT', 'IF', 'PLUS', 'STAR', 'QUESTION', 'CURRENT_TIMESTAMP', 'JAVASCRIPT', 'NEW', 'CAST', 'CONVERT', 'SUM', 'COUNT', 'MIN', 'MAX', 'AVG', 'FIRST', 'LAST', 'AGGR', 'ARRAY', 'REPLACE', 'DATEADD', 'DATEDIFF', 'INTERVAL', 'TRUE', 'FALSE', 'NSTRING', 'NULL', 'EXISTS', 'ARRAYLBRA', 'BRAQUESTION', 'CASE', 'TILDA', 'MINUS', 'ATLBRA', 'LCUR', got 'EOF'"}
```

The following request fails for example:
```
<feature layer URL>/query?f=json&outFields=%20domain%2cOBJECTID&where=1%20%3d%201&resultOffset=0&resultRecordCount=200&returnGeometry=false&orderByFields=%20domain%20ASC%2c%20OBJECTID%20ASC
```

**Comment by jkerr5** [comment]
Here's a full trace for this error:
```
Trace: SyntaxError: Parse error on line 1:
...rties->`domain` ASC,
-----------------------^
Expecting 'LITERAL', 'BRALITERAL', 'LPAR', 'NUMBER', 'STRING', 'SHARP', 'DOLLAR', 'AT', 'VALUE', 'COLON', 'NOT', 'IF', 'PLUS', 'STAR', 'QUESTION', 'CURRENT_TIMESTAMP', 'JAVASCRIPT', 'NEW', 'CAST', 'CONVERT', 'SUM', 'COUNT', 'MIN', 'MAX', 'AVG', 'FIRST', 'LAST', 'AGGR', 'ARRAY', 'REPLACE', 'DATEADD', 'DATEDIFF', 'INTERVAL', 'TRUE', 'FALSE', 'NSTRING', 'NULL', 'EXISTS', 'ARRAYLBRA', 'BRAQUESTION', 'CASE', 'TILDA', 'MINUS', 'ATLBRA', 'LCUR', got 'EOF'
    at Parser.parser.parseError (/koop/node_modules/alasql/dist/alasql.fs.js:2211:8)
    at Parser.parse (/koop/node_modules/alasql/dist/alasql.fs.js:2085:22)
    at Function.alasql.parse (/koop/node_modules/alasql/dist/alasql.fs.js:4425:22)
    at Function.alasql.dexec (/koop/node_modules/alasql/dist/alasql.fs.js:4618:19)
    at Function.alasql.exec (/koop/node_modules/alasql/dist/alasql.fs.js:4595:17)
    at alasql (/koop/node_modules/alasql/dist/alasql.fs.js:138:16)
    at standardQuery (/koop/node_modules/winnow/dist/executeQuery.js:33:18)
    at Object.Winnow.query (/koop/node_modules/winnow/dist/index.js:33:17)
    at query (/koop/node_modules/featureserver/dist/query.js:38:56)
    at execQuery (/koop/node_modules/featureserver/dist/route.js:51:16)
    at Object.route (/koop/node_modules/featureserver/dist/route.js:40:14)
    at /koop/node_modules/koop-output-geoservices/index.js:16:24
    at /koop/node_modules/koop/dist/models/index.js:15:9
    at mq.providerGetData.then.data (/koop/marklogic.js:45:8)
    at <anonymous>
    at execQuery (/koop/node_modules/featureserver/dist/route.js:53:52)
    at Object.route (/koop/node_modules/featureserver/dist/route.js:40:14)
    at /koop/node_modules/koop-output-geoservices/index.js:16:24
    at /koop/node_modules/koop/dist/models/index.js:15:9
    at mq.providerGetData.then.data (/koop/marklogic.js:45:8)
    at <anonymous>
```

**Comment by rgwozdz** [comment]
@jkerr5 thanks for reporting this.  I'd be happy to to take this on, unless you already have a PR in progress.

**Comment by jkerr5** [comment]
I haven't started on anything yet so an update from your side would be great!

**Comment by jkerr5** [comment]
Winnow version 1.16.3
Alasql version 0.4.11

**Comment by rgwozdz** [comment]
Hmm, ok.  I didn't get the same error as you.  But I did find something else amiss with `orderByFields` and have PR https://github.com/koopjs/winnow/pull/99 to address it.  Maybe its related to what you are seeing.

**Comment by rgwozdz** [comment]
@jkerr5 please try upgrading to latest winnow (1.16.4) and let me know if this solves the issue.

**Comment by jkerr5** [comment]
Yes, this looks resolved now. Thanks!
