### ISSUE TITLE
Allow server info customization.

### ISSUE THREAD

**Issue by hparkertt** [koopjs/FeatureServer#170]
In [src/info.js](https://github.com/koopjs/FeatureServer/blob/master/src/info.js), the [`serverLayerInfo`](https://github.com/koopjs/FeatureServer/blob/master/src/info.js#L42) function does not allow for the `id`, `defaultVisibility`, `minScale`, or `maxScale` properties to be provided by the metadata object.  I think it would be beneficial to allow for these properties to be overwritten by the metadata object.  Upon further research, the same can be said of the [`renderLayer`](https://github.com/koopjs/FeatureServer/blob/master/src/templates.js#L32) function in [src/templates.js](https://github.com/koopjs/FeatureServer/blob/master/src/templates.js).

A quick and simple fix would be to provide the logic to pull these properties off of the metadata object in these two functions.  However, I wonder if there is an opportunity for consolidation of logic here?  Is there a reason why the [`serverLayerInfo`](https://github.com/koopjs/FeatureServer/blob/master/src/info.js#L42) function shouldn't utilize the [`renderLayer`](https://github.com/koopjs/FeatureServer/blob/master/src/templates.js#L32) function (or even the [`layerInfo`](https://github.com/koopjs/FeatureServer/blob/master/src/info.js#L38) function in [src/info.js](https://github.com/koopjs/FeatureServer/blob/master/src/info.js)) to consistently build up the layer info object?  Another potential improvement could be the inclusion of the `spread` operator (`...`) to allow for all properties to be overwritten dynamically.  This would involve some manipulation of the metadata object, since not all properties currently supported by the metadata object are valid properties on the resulting info object.  However, this could be a good, flexible approach to allow for developers to overwrite any property on the info object using the metadata object.

**Comment by rgwozdz** [comment]
@hparkertt thanks very much for your thoughts on this.  Do you have interest putting these ideas into a PR and submitting for review?  We're always looking for thoughtful contributions.

**Comment by hparkertt** [comment]
Sure, I don't mind taking a pass at this.  Do you have any thoughts on the approach?

**Comment by rgwozdz** [comment]
Generally speaking, there is a lot of opportunity to refactor/consolidate logic.  I'm actually out of the  office / offline this week, so it's a bit difficult for me to scrutinize the code you are referring to.  But I think `serverLayerInfo` provides a subset of layer info used in the server info response `/FeatureServer` while `layerInfo` provides the response used for the layer `FeatureServer/0`.  I think the spread operator idea is a good one.  I would maybe do some schema checking with Joi to ensure the resulting properties and value types are correct.  ArcGIS clients are particularly sensitive to the server and layer info responses.

**Comment by hparkertt** [comment]
I'll take a look and see what I can come up with.  It may be that I create to PRs, one for the 'quick' solution and a branch for a possible logic refactoring.  This probably wont happen until after the holiday, so feel free to add comments/code/ideas to this ticket as you have time to review the logic mentioned.

**Comment by hparkertt** [comment]
@rgwozdz I have the 'quick' solution in my workspace, but I am running into some testing issues.  When I run the test command (without any of my changes) I'm getting 8 errors.  I've pulled down a fresh version and I'm getting the same results.  After cloning, I'm running:
`npm install`
`npm run compile`
`npm run test`

Here's the output of the 8 errors I'm getting:
```
  127 passing (1s)
  8 failing

  1) Query operations
       when using an outSR
         should translate the data properly:

      AssertionError: expected 1159001264 to be 1138516379
      + expected - actual

      -1159001264
      +1138516379

      at Assertion.fail (node_modules\should\cjs\should.js:275:17)
      at Assertion.value (node_modules\should\cjs\should.js:356:19)
      at Context.<anonymous> (test\query.js:70:55)

  2) Query operations
       when getting featureserver features by id queries
         should return a proper features:
     AssertionError: expected Array [] to have property length of 3 (got 0)
      at Assertion.fail (node_modules\should\cjs\should.js:275:17)
      at Assertion.value (node_modules\should\cjs\should.js:356:19)
      at Context.it (test\query.js:91:37)

  3) Query operations
       when getting featureserver features by id queries
         should work with single id:
     AssertionError: expected Array [] to have property length of 1 (got 0)
      at Assertion.fail (node_modules\should\cjs\should.js:275:17)
      at Assertion.value (node_modules\should\cjs\should.js:356:19)
      at Context.it (test\query.js:98:37)

  4) Query operations
       when getting featureserver features by id queries
         should return only count of features:

      AssertionError: expected 0 to be 3
      + expected - actual

      -0
      +3

      at Assertion.fail (node_modules\should\cjs\should.js:275:17)
      at Assertion.value (node_modules\should\cjs\should.js:356:19)
      at Context.it (test\query.js:105:29)

  5) Query operations
       when getting features with returnIdsOnly
         should return only ids of features:

      AssertionError: expected 0 to be 3
      + expected - actual

      -0
      +3

      at Assertion.fail (node_modules\should\cjs\should.js:275:17)
      at Assertion.value (node_modules\should\cjs\should.js:356:19)
      at Context.it (test\query.js:122:40)

  6) Routing feature server requests
       Query
         should properly route and handle a query:

      AssertionError: expected 1231184206 to be 1954528849
      + expected - actual

      -1231184206
      +1954528849

      at Assertion.fail (node_modules\should\cjs\should.js:275:17)
      at Assertion.value (node_modules\should\cjs\should.js:356:19)
      at request.get.expect.res (test\route.js:181:59)
      at Test._assertFunction (node_modules\supertest\lib\test.js:283:11)
      at Test.assert (node_modules\supertest\lib\test.js:173:18)
      at Server.localAssert (node_modules\supertest\lib\test.js:131:12)
      at emitCloseNT (net.js:1618:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  7) Routing feature server requests
       Query
         should respect passed in max record count:

      AssertionError: expected 1231184206 to be 1954528849
      + expected - actual

      -1231184206
      +1954528849

      at Assertion.fail (node_modules\should\cjs\should.js:275:17)
      at Assertion.value (node_modules\should\cjs\should.js:356:19)
      at request.get.expect.res (test\route.js:194:59)
      at Test._assertFunction (node_modules\supertest\lib\test.js:283:11)
      at Test.assert (node_modules\supertest\lib\test.js:173:18)
      at Server.localAssert (node_modules\supertest\lib\test.js:131:12)
      at emitCloseNT (net.js:1618:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  8) Routing feature server requests
       Query
         should ignore empty query parameters:

      AssertionError: expected 1231184206 to be 1954528849
      + expected - actual

      -1231184206
      +1954528849

      at Assertion.fail (node_modules\should\cjs\should.js:275:17)
      at Assertion.value (node_modules\should\cjs\should.js:356:19)
      at request.get.expect.res (test\route.js:228:59)
      at Test._assertFunction (node_modules\supertest\lib\test.js:283:11)
      at Test.assert (node_modules\supertest\lib\test.js:173:18)
      at Server.localAssert (node_modules\supertest\lib\test.js:131:12)
      at emitCloseNT (net.js:1618:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

Is this something you've seen before?  Is there an expectation of some global package(s) that I may be missing?

Any help you can provide would be greatly appreciated!

**Comment by rgwozdz** [comment]
Yeah, this is familiar.  Trying to recall what causes this. What version of node are you using?

**Comment by hparkertt** [comment]
Node: 10.16.0
npm: 6.9.0

**Comment by rgwozdz** [comment]
When I use Node 10 it passes, Node 8 it fails.  Odd that 10.16 is failing for you.  What OS are you on?

It comes from the farm-hash package, which appears to produce different numeric hashes under different versions of node (I guess).

**Comment by hparkertt** [comment]
Huh, that's odd.

I'm running on Windows.  Based on the `rm -rf dist` in the package.json, I'm guessing you're unix based?

**Comment by rgwozdz** [comment]
Yes, unix-based. I guess this demo's the need to make these tests less brittle.

**Comment by rgwozdz** [comment]
You could comment out the tests for now, work on your PR, and we'll figure out what to do when you submit.

**Comment by hparkertt** [comment]
Sounds good, I'll pick this up tomorrow.  Thanks!

**Comment by hparkertt** [comment]
@rgwozdz I adjusted the testing to be a little more dynamic, which resolved the OBJECTID issue mentioned above.  Would you mind testing it on your setup as well to make sure I didn't break things there?  Thanks!

**Comment by rgwozdz** [comment]
Will do!  Thanks very much!

**Comment by haoliangyu** [comment]
It may be worth to have travis test on different OSs.
