### ISSUE TITLE
Error setting displayField when there are no fields

### ISSUE THREAD

**Issue by dmfenton** [koopjs/FeatureServer#98]
Trace: TypeError: Cannot read property 'name' of undefined
    at renderLayer (/Users//koop/providers/yelp/server/node_modules/featureserver/dist/templates.js:67:88)
    at Object.layerInfo (/Users//koop/providers/yelp/server/node_modules/featureserver/dist/info.js:37:10)

**Comment by rgwozdz** [comment]
Fixed in e6439dfb9379797c998909cd662389cec6c21e1c
